language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install -y collectd collectd-core

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.3-5.5-alpha

matrix:
  allow_failures:
  - python: pypy3.3-5.5-alpha

install:
  # workaround for travis build vm's and multiprocessing
  # see https://github.com/travis-ci/travis-core/issues/187
  - sudo rm -rf /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
  # install dependencies
  - pip install -r requirements.txt
  - pip install "coverage>=3.6" "nose>=1.3.0" "flake8>=2.1" "coveralls>=0.3"
  # install bucky
  - pip install -e .

script:
  - flake8 --show-source --ignore=E501,E731,W391 .
  - nosetests -v --with-coverage tests/test_000_bucky.py
  - nosetests -v --with-coverage tests/test_001_statsd.py
  - PYTHONPATH="." python contrib/statsd_perfomance_test.py

after_success:
  - coveralls
