language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  # workaround for travis build vm's and multiprocessing
  # see https://github.com/travis-ci/travis-core/issues/187
  - sudo rm -rf /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
  # install dependencies
  - pip install -r requirements.txt
  # install bucky
  - pip install -e .

script:
  - PYTHONPATH="." python -m unittest tests/test_*.py
